### PR TITLE
fix context menu despawn rerender bug

### LINKED ISSUE #207: despawnContextMenu action creator shouldn't affect state if context menu isn't already displaying
Right now, any left click triggers a re-render of the relevant component because it dispatches the `despawnContextMenu` action, whether or not the context menu is displaying. To fix: simply stop the action if the context menu is not currently displaying.

### PR DESCRIPTION
**Pull request by davidvorona**
Key features:
- reminds me of that one family guy cutaway where Peter starts acting iamverysmart and Brian comments on the "classics" in his bookshelf, before Stewie exposes the fact that he hasn't actually read any of them
- "what is this, oak? ohhhh i don't even think it's oak"
- https://www.youtube.com/watch?v=HRvNYaGiLjg

Closes #207

### CODE REVIEW

File: client/game/reducers/utils.js [hunk 1]
```diff
@@ -77,7 +77,10 @@ const utils = (state = [], action) => {
             ...state,
             contextMenu: action.contextMenu
         };
-    case 'DESPAWN_CONTEXT_MENU':
+    case 'DESPAWN_CONTEXT_MENU': {
+        if (!state.contextMenu.show) {
```
Comment (evanw555) [inline client/game/reducers/utils.js]: Is this oak?
